-- Insert sample blog posts for demonstration
INSERT INTO blog_posts (
  title,
  slug,
  content,
  excerpt,
  status,
  is_featured,
  published_at,
  reading_time_minutes,
  featured_image_url,
  tags,
  meta_title,
  meta_description
) VALUES
(
  'Welcome to NeighborLink Community',
  'welcome-to-neighborlink-community',
  '<h2>Building Stronger Neighborhoods Together</h2><p>NeighborLink is more than just a platform—it''s a movement to reconnect communities and foster meaningful relationships with the people who live around you.</p><p>In today''s fast-paced world, we often forget the value of knowing our neighbors. NeighborLink brings back that sense of community by making it easy to connect, share, and support one another.</p><h3>What Makes NeighborLink Special?</h3><p>Our platform is designed with safety, privacy, and genuine connection in mind. Whether you need help with a project, want to organize a neighborhood event, or simply want to meet the people next door, NeighborLink makes it simple and secure.</p>',
  'Discover how NeighborLink is revolutionizing the way neighbors connect, share resources, and build stronger communities together.',
  'published',
  true,
  NOW(),
  5,
  'https://images.unsplash.com/photo-1511632765486-a01980e01a18?w=800&q=80',
  ARRAY['community', 'welcome', 'getting-started'],
  'Welcome to NeighborLink - Building Stronger Communities',
  'Join the NeighborLink community and discover how easy it is to connect with neighbors, share resources, and build a stronger local community.'
),
(
  '5 Ways to Get Involved in Your Community',
  '5-ways-to-get-involved-in-your-community',
  '<h2>Make a Difference Where You Live</h2><p>Getting involved in your local community is one of the most rewarding things you can do. Here are five simple ways to start making a difference today.</p><h3>1. Attend Local Events</h3><p>Check out neighborhood gatherings, farmers markets, and community meetings. These are great opportunities to meet your neighbors and learn about local initiatives.</p><h3>2. Volunteer Your Time</h3><p>Many community organizations are always looking for volunteers. Whether it''s helping at a food bank, cleaning up parks, or mentoring youth, your time makes a real impact.</p><h3>3. Support Local Businesses</h3><p>Shopping local keeps money in your community and helps small businesses thrive. Plus, you''ll often get better service and unique products.</p><h3>4. Share Your Skills</h3><p>Everyone has something valuable to offer. Whether you''re good at gardening, tech support, or cooking, sharing your knowledge strengthens community bonds.</p><h3>5. Start Small Conversations</h3><p>Sometimes the simplest actions have the biggest impact. Say hello to neighbors, start a conversation at the mailbox, or organize a casual get-together.</p>',
  'Looking to make a positive impact in your neighborhood? Here are five practical ways to get more involved and build stronger community connections.',
  'published',
  false,
  NOW() - INTERVAL '2 days',
  8,
  'https://images.unsplash.com/photo-1529156069898-49953e39b3ac?w=800&q=80',
  ARRAY['community', 'tips', 'volunteering'],
  '5 Ways to Get Involved in Your Community',
  'Discover practical ways to get involved in your local community and make a positive impact where you live.'
),
(
  'Safety Tips for Neighborhood Connections',
  'safety-tips-for-neighborhood-connections',
  '<h2>Staying Safe While Building Community</h2><p>Connecting with neighbors is wonderful, but it''s important to prioritize your safety. Here are essential tips for secure community engagement.</p><h3>Verify Identities</h3><p>Always verify who you''re connecting with. NeighborLink uses verification systems to help ensure community members are who they say they are.</p><h3>Meet in Public Spaces First</h3><p>When meeting someone for the first time, choose public locations like coffee shops or community centers. This keeps interactions comfortable and safe for everyone.</p><h3>Trust Your Instincts</h3><p>If something feels off, it probably is. Never feel pressured to share personal information or meet someone if you''re not comfortable.</p><h3>Use Platform Features</h3><p>Take advantage of NeighborLink''s built-in safety features like verified profiles, secure messaging, and community reporting tools.</p><h3>Share Wisely</h3><p>Be mindful about what personal information you share online. Keep sensitive details private until you''ve built trust with community members.</p>',
  'Learn essential safety tips for connecting with neighbors and building community relationships while protecting your privacy and security.',
  'published',
  false,
  NOW() - INTERVAL '5 days',
  6,
  'https://images.unsplash.com/photo-1516321497487-e288fb19713f?w=800&q=80',
  ARRAY['safety', 'tips', 'security'],
  'Safety Tips for Neighborhood Connections',
  'Essential safety tips for connecting with neighbors while protecting your privacy and security in your local community.'
),
(
  'The Power of Local Resource Sharing',
  'the-power-of-local-resource-sharing',
  '<h2>Building a Sharing Economy in Your Neighborhood</h2><p>Imagine a community where you can borrow a ladder, share tools, or find help with projects without spending money. That''s the power of local resource sharing.</p><h3>Environmental Benefits</h3><p>Sharing resources reduces waste and consumption. When neighbors share tools and equipment, we need fewer products overall, which is better for our planet.</p><h3>Financial Savings</h3><p>Why buy expensive tools you''ll use once when you can borrow from a neighbor? Resource sharing saves everyone money while building community bonds.</p><h3>Skill Exchanges</h3><p>Resource sharing isn''t just about physical items. Exchanging skills and knowledge creates a richer, more capable community where everyone benefits.</p><h3>Getting Started</h3><p>Start small by offering to share something you have or asking to borrow something you need. Use NeighborLink to post what you''re willing to share and see what others are offering.</p>',
  'Explore how sharing resources with neighbors can save money, reduce waste, and build stronger community connections.',
  'published',
  false,
  NOW() - INTERVAL '7 days',
  7,
  'https://images.unsplash.com/photo-1556911220-bff31c812dba?w=800&q=80',
  ARRAY['sharing', 'sustainability', 'community'],
  'The Power of Local Resource Sharing',
  'Discover how sharing resources with neighbors can save money, reduce environmental impact, and strengthen community bonds.'
),
(
  'Organizing Successful Neighborhood Events',
  'organizing-successful-neighborhood-events',
  '<h2>Bringing Your Community Together</h2><p>Neighborhood events are fantastic for building connections and creating a sense of belonging. Here''s how to organize events that bring people together.</p><h3>Start with Simple Ideas</h3><p>You don''t need elaborate plans. A casual BBQ, game night, or seasonal gathering can be just as effective as larger events.</p><h3>Use Technology Wisely</h3><p>NeighborLink makes it easy to spread the word about your event, manage RSVPs, and coordinate details with attendees.</p><h3>Be Inclusive</h3><p>Consider the diverse needs of your community. Offer activities for different age groups, dietary options, and accessible locations.</p><h3>Delegate Tasks</h3><p>Don''t try to do everything yourself. Ask neighbors to help with setup, food, or activities. Shared responsibility builds ownership and engagement.</p><h3>Follow Up</h3><p>After the event, thank participants and share photos. This maintains momentum and encourages people to attend future gatherings.</p>',
  'Learn how to plan and execute neighborhood events that bring your community together and create lasting connections.',
  'published',
  false,
  NOW() - INTERVAL '10 days',
  9,
  'https://images.unsplash.com/photo-1511795409834-ef04bbd61622?w=800&q=80',
  ARRAY['events', 'community', 'planning'],
  'Organizing Successful Neighborhood Events',
  'A practical guide to planning and executing neighborhood events that bring your community together and foster meaningful connections.'
),
(
  'Building Trust in Your Neighborhood',
  'building-trust-in-your-neighborhood',
  '<h2>The Foundation of Strong Communities</h2><p>Trust is the cornerstone of vibrant neighborhoods. Here''s how to build and maintain trust within your community.</p><h3>Consistency is Key</h3><p>Show up regularly. Attend community meetings, wave to neighbors, and be a reliable presence. Consistent engagement builds familiarity and trust.</p><h3>Keep Your Commitments</h3><p>If you say you''ll do something, follow through. Whether it''s returning borrowed items on time or showing up when you said you would, reliability matters.</p><h3>Practice Active Listening</h3><p>When neighbors share concerns or ideas, listen attentively. Understanding different perspectives builds empathy and stronger relationships.</p><h3>Be Transparent</h3><p>Honest communication prevents misunderstandings. If issues arise, address them directly and kindly rather than letting them fester.</p><h3>Celebrate Diversity</h3><p>Embrace the different backgrounds, perspectives, and experiences in your community. Diversity strengthens neighborhoods when we approach it with openness.</p>',
  'Discover practical strategies for building trust and creating a foundation of strong, meaningful relationships in your neighborhood.',
  'published',
  false,
  NOW() - INTERVAL '12 days',
  7,
  'https://images.unsplash.com/photo-1521791136064-7986c2920216?w=800&q=80',
  ARRAY['trust', 'community', 'relationships'],
  'Building Trust in Your Neighborhood',
  'Learn how to build and maintain trust within your neighborhood community for stronger, more meaningful relationships.'
);