// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { getSafeStorage } from '@/utils/iosCompatibility';

const SUPABASE_URL = "https://cowiviqhrnmhttugozbz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNvd2l2aXFocm5taHR0dWdvemJ6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMwNTQ0NDQsImV4cCI6MjA2ODYzMDQ0NH0.BJ6OstIOar6CqEv__WzF9qZYaW12uQ-FfXYaVdxgJM4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Get safe storage for iOS compatibility (handles private browsing)
const storage = getSafeStorage();

// Detect iOS device
const isIOS = /iPad|iPhone|iPod/.test(navigator.userAgent);

// Enhanced error handling for iOS Safari security restrictions
const createSupabaseClient = () => {
  try {
    const clientConfig: any = {
      auth: {
        storage,
        persistSession: true,
        autoRefreshToken: true,
        detectSessionInUrl: true, // Enable for iOS email verification deep links
        storageKey: 'neighborlink-auth',
        flowType: 'pkce', // More secure auth flow for iOS
      },
      global: {
        headers: {
          'X-Client-Info': 'neighborlink-ios-compat',
          'Cache-Control': 'no-cache',
        },
        fetch: (url, options = {}) => {
          // Enhanced fetch with iOS security error handling
          const enhancedOptions = {
            ...options,
            credentials: 'same-origin' as RequestCredentials,
            mode: 'cors' as RequestMode,
          };
          
          return fetch(url, enhancedOptions).catch((error) => {
            if (error.name === 'SecurityError' || error.message?.includes('insecure')) {
              console.warn('iOS Safari security restriction detected, retrying with fallback');
              // Retry with minimal options
              return fetch(url, {
                ...options,
                credentials: 'omit' as RequestCredentials,
                mode: 'cors' as RequestMode,
              });
            }
            throw error;
          });
        },
      },
    };

    // Only enable realtime on non-iOS devices or with careful error handling
    if (!isIOS) {
      clientConfig.realtime = {
        params: {
          eventsPerSecond: 2,
        },
        heartbeatIntervalMs: 30000,
        reconnectAfterMs: (tries: number) => Math.min(tries * 1000, 30000),
      };
    } else {
      // Disable realtime on iOS to prevent WebSocket SecurityError
      console.log('iOS detected: Realtime features disabled to prevent security errors');
    }

    return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, clientConfig);
  } catch (error) {
    console.error('Failed to create Supabase client:', error);
    // Don't throw on iOS if it's a SecurityError - allow degraded functionality
    if (isIOS && (error as any)?.name === 'SecurityError') {
      console.warn('iOS SecurityError caught during client creation, using fallback configuration');
      return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
        auth: {
          storage,
          persistSession: true,
          autoRefreshToken: true,
          detectSessionInUrl: true,
          storageKey: 'neighborlink-auth',
          flowType: 'pkce',
        },
      });
    }
    throw new Error('Unable to initialize secure connection. Please try refreshing the page.');
  }
};

export const supabase = createSupabaseClient();

// Aggressive session refresh and validation
const validateAndRefreshSession = async () => {
  try {
    const { data: { session }, error } = await supabase.auth.getSession();
    
    if (error) {
      console.error('Session validation error:', error);
      return;
    }
    
    if (session) {
      // Check if token is about to expire (within 5 minutes)
      const expiresAt = session.expires_at ? session.expires_at * 1000 : 0;
      const now = Date.now();
      const fiveMinutes = 5 * 60 * 1000;
      
      if (expiresAt - now < fiveMinutes) {
        console.log('Token expiring soon, refreshing...');
        const { error: refreshError } = await supabase.auth.refreshSession();
        if (refreshError) {
          console.error('Session refresh failed:', refreshError);
        } else {
          console.log('Session refreshed successfully');
        }
      }
    }
  } catch (error) {
    console.error('Error in validateAndRefreshSession:', error);
  }
};

// Add visibility change listener to refresh session when app comes to foreground
if (typeof document !== 'undefined') {
  document.addEventListener('visibilitychange', () => {
    if (document.visibilityState === 'visible') {
      console.log('App became visible, validating session');
      validateAndRefreshSession();
    }
  });

  // Validate session on startup
  validateAndRefreshSession();

  // Monitor localStorage for session changes (multi-tab support)
  window.addEventListener('storage', (event) => {
    if (event.key?.startsWith('sb-') && event.key?.includes('auth-token')) {
      console.log('Auth storage changed, revalidating session');
      validateAndRefreshSession();
    }
  });
}