// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { getSafeStorage } from '@/utils/iosCompatibility';
import { nativeStorageAdapter } from '@/utils/nativeStorageAdapter';

const SUPABASE_URL = "https://cowiviqhrnmhttugozbz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNvd2l2aXFocm5taHR0dWdvemJ6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMwNTQ0NDQsImV4cCI6MjA2ODYzMDQ0NH0.BJ6OstIOar6CqEv__WzF9qZYaW12uQ-FfXYaVdxgJM4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Detect iOS device
const isIOS = /iPad|iPhone|iPod/.test(navigator.userAgent);

// Safe Capacitor detection with defensive fallback
const getCapacitor = () => {
  try {
    // Try importing Capacitor - will only work if @capacitor/core is available
    const { Capacitor } = require('@capacitor/core');
    return Capacitor;
  } catch (error) {
    // Capacitor not available (web mode)
    return null;
  }
};

// Safe storage detection with defensive fallback
const getStorageAdapter = () => {
  try {
    const Capacitor = getCapacitor();
    const isNativePlatform = Capacitor?.isNativePlatform?.() === true;
    if (isNativePlatform) {
      return nativeStorageAdapter;
    }
    return getSafeStorage();
  } catch (error) {
    console.warn('Storage detection failed, using fallback:', error);
    return getSafeStorage();
  }
};

// Enhanced error handling for iOS Safari security restrictions
const createSupabaseClient = () => {
  try {
    const storage = getStorageAdapter();
    
    const clientConfig: any = {
      auth: {
        storage,
        persistSession: true,
        autoRefreshToken: true,
        detectSessionInUrl: true, // Enable for iOS email verification deep links
        storageKey: 'neighborlink-auth',
        flowType: 'pkce', // More secure auth flow for iOS
      },
      global: {
        headers: {
          'X-Client-Info': 'neighborlink-ios-compat',
          'Cache-Control': 'no-cache',
        },
      },
    };

    // Enable realtime for all devices with optimized settings
    clientConfig.realtime = {
      params: {
        eventsPerSecond: 10, // Increased for faster message delivery
      },
      heartbeatIntervalMs: 15000, // More frequent heartbeats for better connection
      reconnectAfterMs: (tries: number) => Math.min(tries * 500, 5000), // Faster reconnection
    };

    return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, clientConfig);
  } catch (error) {
    console.error('Failed to create Supabase client:', error);
    // Don't throw on iOS if it's a SecurityError - allow degraded functionality
    if (isIOS && (error as any)?.name === 'SecurityError') {
      console.warn('iOS SecurityError caught during client creation, using fallback configuration');
      const fallbackStorage = getStorageAdapter();
      return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
        auth: {
          storage: fallbackStorage,
          persistSession: true,
          autoRefreshToken: true,
          detectSessionInUrl: true,
          storageKey: 'neighborlink-auth',
          flowType: 'pkce',
        },
      });
    }
    throw new Error('Unable to initialize secure connection. Please try refreshing the page.');
  }
};

export const supabase = createSupabaseClient();

// Aggressive session refresh and validation
const validateAndRefreshSession = async () => {
  try {
    const { data: { session }, error } = await supabase.auth.getSession();
    
    if (error) {
      console.error('Session validation error:', error);
      return;
    }
    
    if (session) {
      // Check if token is about to expire (within 5 minutes)
      const expiresAt = session.expires_at ? session.expires_at * 1000 : 0;
      const now = Date.now();
      const fiveMinutes = 5 * 60 * 1000;
      
      if (expiresAt - now < fiveMinutes) {
        console.log('Token expiring soon, refreshing...');
        const { error: refreshError } = await supabase.auth.refreshSession();
        if (refreshError) {
          console.error('Session refresh failed:', refreshError);
        } else {
          console.log('Session refreshed successfully');
        }
      }
    }
  } catch (error) {
    console.error('Error in validateAndRefreshSession:', error);
  }
};

// Add visibility change listener to refresh session when app comes to foreground
if (typeof document !== 'undefined') {
  document.addEventListener('visibilitychange', () => {
    if (document.visibilityState === 'visible') {
      console.log('App became visible, validating session');
      validateAndRefreshSession();
    }
  });

  // Validate session on startup
  validateAndRefreshSession();

  // Monitor localStorage for session changes (multi-tab support)
  window.addEventListener('storage', (event) => {
    if (event.key?.startsWith('sb-') && event.key?.includes('auth-token')) {
      console.log('Auth storage changed, revalidating session');
      validateAndRefreshSession();
    }
  });
}